// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sourlbyrizlsrzfzqmbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdXJsYnlyaXpsc3J6ZnpxbWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTAxNDQsImV4cCI6MjA2MTcyNjE0NH0.Q-a5x1-rG8hU7_wk6PHwkBk9MnSn2RRp9_XCAT5Uk9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);